# Generated by Django 5.0.6 on 2024-06-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='education_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ky',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_ky',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_ru',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
